[package]
name = "rust-cta"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"
rstest = "0.16.0"
serde = "1.0.152"
serde_derive = "1.0.152"
serde_json = "1.0.91"
ureq = "2.6.2"
